; ===================================================================
;  pjsip.conf - Usuarios SIP del Asterisk
;
;  Bind explicito a 192.168.56.10 (red host-only).
;  rtp_symmetric=yes + force_rport=yes + rewrite_contact=yes
;  hacen que Asterisk mande SIP/RTP a la IP REAL desde la que vino el
;  paquete, ignorando lo que diga el SDP. Esto resuelve el problema
;  clasico de softphones multihomed que anuncian la IP equivocada.
; ===================================================================

[transport-udp]
type            = transport
protocol        = udp
bind            = 192.168.56.10:5060

[endpoint-template](!)
type            = endpoint
context         = from-internal
disallow        = all
allow           = ulaw
allow           = alaw
direct_media    = no
rtp_symmetric   = yes
force_rport     = yes
rewrite_contact = yes

[auth-template](!)
type            = auth
auth_type       = userpass

[aor-template](!)
type            = aor
max_contacts    = 1
remove_existing = yes

; -------------------------------------------------------------------
;  Extension 1001
; -------------------------------------------------------------------
[1001](endpoint-template)
auth            = 1001-auth
aors            = 1001
callerid        = "Softphone 1001" <1001>

[1001-auth](auth-template)
username        = 1001
password        = TaxiPass1001!

[1001](aor-template)

; -------------------------------------------------------------------
;  Extension 1002
; -------------------------------------------------------------------
[1002](endpoint-template)
auth            = 1002-auth
aors            = 1002
callerid        = "Softphone 1002" <1002>

[1002-auth](auth-template)
username        = 1002
password        = TaxiPass1002!

[1002](aor-template)
